name: 'ecommerce_data_platform'

version: '1.0.0'

config-version: 2

profile: 'ecommerce_data_platform'

model-paths: ["models"]

target-path: "target"

clean-targets:
  - "target"

models:

  ecommerce_data_platform:

    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: marts
      +materialized: table