services:

  postgres:
    image: postgres:15
    container_name: ecommerce_postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "8084:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      - postgres

    restart: unless-stopped
  
  dbt:
    build:
      context: ./dbt

    container_name: ecommerce_dbt

    volumes:
      - ./dbt:/usr/app/dbt
      - ./data:/usr/app/data

    working_dir: /usr/app/dbt

    ports:
    - "8085:8085"

    depends_on:
      - postgres

    tty: true
  
  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile

    container_name: ecommerce_ingestion

    volumes:
      - .:/usr/app

    working_dir: /usr/app

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    depends_on:
      - postgres

    tty: true    

volumes:
  postgres_data:
  pgadmin_data: