from typing import Any

from ai_assistant.app.db import execute_select_query
from ai_assistant.app.sql_generator import generate_sql
from ai_assistant.app.sql_guard import validate_sql


def summarize_result(question: str, rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "No data found for this question."

    return (
        f"Found {len(rows)} result rows for the question: '{question}'. "
        "SQL was generated by the configured AI provider and validated before execution."
    )


def answer_question(question: str) -> dict[str, Any]:
    generated_sql = generate_sql(question)
    safe_sql = validate_sql(generated_sql)
    rows = execute_select_query(safe_sql)
    summary = summarize_result(question, rows)

    return {
        "question": question,
        "sql": safe_sql,
        "summary": summary,
        "row_count": len(rows),
        "rows": rows,
    }